### PR TITLE
Add results page

### PR DESCRIPTION
**Pull request by 19946-Dresden-St**
### Summary
Add results page

### Details
- results page: created page and added 2 typed of cards (for artist and for studio)
- card component: created a component which managers both the typed created

### Important
I attest on my honor that: 
- [x] I formatted my code
- [x] I commented my code
- [x] I made my code as clear as possible
- [x] I ran all the test and that they successfully pass
- [x] I named my commit by following a good convention
- [x] I didn't push conflicted code

### CODE REVIEW

**Comment by AtoLrn** [comment]
Tu peux mettre une image de l'interface stp ?

**Comment by 19946-Dresden-St** [comment]
interface results page

**Comment by AtoLrn** [comment]
Sur la Hp c'est bien d'avoir la grosse search mais je trouve que sur les pages ou tu as deja fait ta recherche faudrait peut-etre avoir un input de search plus discret

**Comment by 19946-Dresden-St** [comment]
> Sur la Hp c'est bien d'avoir la grosse search mais je trouve que sur les pages ou tu as deja fait ta recherche faudrait peut-etre avoir un input de search plus discret

interface

**Review by Redeltaz — APPROVED** [review]

**Pull request merged**
